M48
; DRILL file {KiCad 8.0.4} date 2024-11-02T17:57:15+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-02T17:57:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0420
%
G90
G05
T1
X4.2809Y-5.2756
X4.3809Y-5.2756
T2
X4.3094Y-4.4488
X4.4094Y-4.4488
T3
X4.3504Y-4.5866
X4.3504Y-5.3937
M30
